version: '3.3'
services:
  nginx:
    container_name: webserver_nginx
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
  php:
    container_name: web_php
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      
    