version: '3.3'
services:
  nginx:
    container_name: webserver_nginx
    build: ./nginx
      
    command: nginx -g "daemon off;"
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    
    networks:
      - web
  php:
    container_name: web_php
    build: ./php
    working_dir: /var/www/html
    networks:
      - web
    volumes:
      - .:/var/www/html
    
networks:
  web:
    driver: bridge
    
      
    